//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbUsuario
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Ap1 { get; set; }
        public string Ap2 { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
